"""Add days_of_week and end_date to route_templates

Revision ID: 24c2d89eaea6
Revises: f051b7b4409e
Create Date: 2026-03-13 05:08:23.790958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c2d89eaea6'
down_revision = 'f051b7b4409e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_of_week', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_templates', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('days_of_week')

    # ### end Alembic commands ###
