"""Add customer_name, driver_name, driver_phone to trips

Revision ID: 6f9cd3e6a9d9
Revises: f1f13405f42b
Create Date: 2026-03-13 07:03:00.048808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9cd3e6a9d9'
down_revision = 'f1f13405f42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('driver_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('driver_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('driver_phone')
        batch_op.drop_column('driver_name')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
