"""add_driver_document_fields

Revision ID: 8ea3626069ca
Revises: aa0976436dd8
Create Date: 2026-03-13 02:15:21.903168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea3626069ca'
down_revision = 'aa0976436dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('license_series', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('license_issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('license_expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('passport_series', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('passport_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('passport_issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('passport_issued_by', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('snils_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tachograph_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tachograph_issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tachograph_expiry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('tachograph_expiry_date')
        batch_op.drop_column('tachograph_issue_date')
        batch_op.drop_column('tachograph_number')
        batch_op.drop_column('snils_number')
        batch_op.drop_column('passport_issued_by')
        batch_op.drop_column('passport_issue_date')
        batch_op.drop_column('passport_number')
        batch_op.drop_column('passport_series')
        batch_op.drop_column('license_expiry_date')
        batch_op.drop_column('license_issue_date')
        batch_op.drop_column('license_series')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
