"""Add driver_id and vehicle_id to route_templates

Revision ID: 924fd7196538
Revises: 8ea3626069ca
Create Date: 2026-03-13 03:22:16.350309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924fd7196538'
down_revision = '8ea3626069ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_route_templates_vehicle_id', 'vehicles', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key('fk_route_templates_driver_id', 'drivers', ['driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_route_templates_vehicle_id', type_='foreignkey')
        batch_op.drop_constraint('fk_route_templates_driver_id', type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
