"""Add driver_phone to route_templates

Revision ID: f051b7b4409e
Revises: 924fd7196538
Create Date: 2026-03-13 03:26:23.165381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f051b7b4409e'
down_revision = '924fd7196538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_templates', schema=None) as batch_op:
        batch_op.drop_column('driver_phone')

    # ### end Alembic commands ###
