"""Add dispatch_time and departure_time to route_templates

Revision ID: f1f13405f42b
Revises: cdde3e06e242
Create Date: 2026-03-13 06:47:56.241431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f13405f42b'
down_revision = 'cdde3e06e242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispatch_time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('departure_time', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_templates', schema=None) as batch_op:
        batch_op.drop_column('departure_time')
        batch_op.drop_column('dispatch_time')

    # ### end Alembic commands ###
